/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EventSenseStorage {
  export type SummaryStruct = {
    cid: string;
    author: AddressLike;
    timestamp: BigNumberish;
  };

  export type SummaryStructOutput = [
    cid: string,
    author: string,
    timestamp: bigint
  ] & { cid: string; author: string; timestamp: bigint };
}

export interface EventSenseStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSummary"
      | "storeSummary"
      | "summaries"
      | "totalSummaries"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SummaryStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeSummary",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "summaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSummaries",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "summaries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSummaries",
    data: BytesLike
  ): Result;
}

export namespace SummaryStoredEvent {
  export type InputTuple = [
    author: AddressLike,
    cid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [author: string, cid: string, timestamp: bigint];
  export interface OutputObject {
    author: string;
    cid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventSenseStorage extends BaseContract {
  connect(runner?: ContractRunner | null): EventSenseStorage;
  waitForDeployment(): Promise<this>;

  interface: EventSenseStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSummary: TypedContractMethod<
    [_index: BigNumberish],
    [EventSenseStorage.SummaryStructOutput],
    "view"
  >;

  storeSummary: TypedContractMethod<[_cid: string], [void], "nonpayable">;

  summaries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        cid: string;
        author: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  totalSummaries: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [EventSenseStorage.SummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeSummary"
  ): TypedContractMethod<[_cid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "summaries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint] & {
        cid: string;
        author: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSummaries"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "SummaryStored"
  ): TypedContractEvent<
    SummaryStoredEvent.InputTuple,
    SummaryStoredEvent.OutputTuple,
    SummaryStoredEvent.OutputObject
  >;

  filters: {
    "SummaryStored(address,string,uint256)": TypedContractEvent<
      SummaryStoredEvent.InputTuple,
      SummaryStoredEvent.OutputTuple,
      SummaryStoredEvent.OutputObject
    >;
    SummaryStored: TypedContractEvent<
      SummaryStoredEvent.InputTuple,
      SummaryStoredEvent.OutputTuple,
      SummaryStoredEvent.OutputObject
    >;
  };
}
